name: CI - Lint and Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - main

jobs:
  ci-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [frontend, backend]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd ${{ matrix.service }}
          npm ci

      - name: Run Lint
        run: |
          cd ${{ matrix.service }}
          npm run lint || echo "Lint warnings ignored"

      - name: Run Tests
        run: |
          cd ${{ matrix.service }}
          npm test -- --watchAll=false
